### ISSUE TITLE
GitHub Actions에 dotnet build 추가

### ISSUE THREAD

**Issue by Bluewak** [oss2025hnu/reposcore-cs#155]
**Is your feature request related to a problem? Please describe.**

현재 이 프로젝트에는 CI 설정이 없어, 단순한 오타나 컴파일 오류 같은 문제도 머지되기 전까지 발견이 어렵습니다.

C#은 정적 타입 언어이기 때문에 `dotnet build`만 실행해도 대부분의 단순한 오류를 조기에 잡아낼 수 있습니다. 따라서 GitHub Actions에 workflow 디렉토리를 생성해서 다음과 같이 최소한의 빌드 파이프라인을 추가하는 것을 제안합니다.

**Specify version (commit id).**
9da18513c5011118bf277991e59417c502cf1d43

**Describe the solution you'd like**
- GitHub Actions에 `dotnet build` 단계 추가
- 대상: `main` 브랜치 기준 PR 및 push 이벤트

아래는 AI로 작성된 YAML입니다. 참고만 해주세요.

```yaml
name: Build .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
```
